
package com.offcn.huigu;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebservice001", targetNamespace = "http://huigu.offcn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebservice001 {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://huigu.offcn.com/", className = "com.offcn.huigu.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://huigu.offcn.com/", className = "com.offcn.huigu.SayHelloResponse")
    @Action(input = "http://huigu.offcn.com/HelloWebservice001/sayHelloRequest", output = "http://huigu.offcn.com/HelloWebservice001/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://huigu.offcn.com/", className = "com.offcn.huigu.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://huigu.offcn.com/", className = "com.offcn.huigu.GetListResponse")
    @Action(input = "http://huigu.offcn.com/HelloWebservice001/getListRequest", output = "http://huigu.offcn.com/HelloWebservice001/getListResponse")
    public List<String> getList();

}
