
package com.offcn.huigu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWebservice001Service", targetNamespace = "http://huigu.offcn.com/", wsdlLocation = "http://10.0.0.70:8087/java001?wsdl")
public class HelloWebservice001Service
    extends Service
{

    private final static URL HELLOWEBSERVICE001SERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWEBSERVICE001SERVICE_EXCEPTION;
    private final static QName HELLOWEBSERVICE001SERVICE_QNAME = new QName("http://huigu.offcn.com/", "HelloWebservice001Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.0.70:8087/java001?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWEBSERVICE001SERVICE_WSDL_LOCATION = url;
        HELLOWEBSERVICE001SERVICE_EXCEPTION = e;
    }

    public HelloWebservice001Service() {
        super(__getWsdlLocation(), HELLOWEBSERVICE001SERVICE_QNAME);
    }

    public HelloWebservice001Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWEBSERVICE001SERVICE_QNAME, features);
    }

    public HelloWebservice001Service(URL wsdlLocation) {
        super(wsdlLocation, HELLOWEBSERVICE001SERVICE_QNAME);
    }

    public HelloWebservice001Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWEBSERVICE001SERVICE_QNAME, features);
    }

    public HelloWebservice001Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebservice001Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWebservice001
     */
    @WebEndpoint(name = "HelloWebservice001Port")
    public HelloWebservice001 getHelloWebservice001Port() {
        return super.getPort(new QName("http://huigu.offcn.com/", "HelloWebservice001Port"), HelloWebservice001.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebservice001
     */
    @WebEndpoint(name = "HelloWebservice001Port")
    public HelloWebservice001 getHelloWebservice001Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://huigu.offcn.com/", "HelloWebservice001Port"), HelloWebservice001.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWEBSERVICE001SERVICE_EXCEPTION!= null) {
            throw HELLOWEBSERVICE001SERVICE_EXCEPTION;
        }
        return HELLOWEBSERVICE001SERVICE_WSDL_LOCATION;
    }

}
