
package com.ooo.aaa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhoneServiceImplService", targetNamespace = "http://service.offcn.com/", wsdlLocation = "http://localhost:8080/0505_PhoneSearch/service/hello?wsdl")
public class PhoneServiceImplService
    extends Service
{

    private final static URL PHONESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PHONESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PHONESERVICEIMPLSERVICE_QNAME = new QName("http://service.offcn.com/", "PhoneServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/0505_PhoneSearch/service/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PHONESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PhoneServiceImplService() {
        super(__getWsdlLocation(), PHONESERVICEIMPLSERVICE_QNAME);
    }

    public PhoneServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONESERVICEIMPLSERVICE_QNAME, features);
    }

    public PhoneServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PHONESERVICEIMPLSERVICE_QNAME);
    }

    public PhoneServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONESERVICEIMPLSERVICE_QNAME, features);
    }

    public PhoneServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServiceImplPort")
    public PhoneService getPhoneServiceImplPort() {
        return super.getPort(new QName("http://service.offcn.com/", "PhoneServiceImplPort"), PhoneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServiceImplPort")
    public PhoneService getPhoneServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.offcn.com/", "PhoneServiceImplPort"), PhoneService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PHONESERVICEIMPLSERVICE_EXCEPTION;
        }
        return PHONESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
