
package com.ooo.aaa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhoneService", targetNamespace = "http://service.offcn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhoneService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ooo.aaa.Phone
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByNumber", targetNamespace = "http://service.offcn.com/", className = "com.ooo.aaa.FindByNumber")
    @ResponseWrapper(localName = "findByNumberResponse", targetNamespace = "http://service.offcn.com/", className = "com.ooo.aaa.FindByNumberResponse")
    public Phone findByNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
