
package com.offcn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWebserviceService", targetNamespace = "http://offcn.com/", wsdlLocation = "http://localhost:9999/hello?wsdl")
public class HelloWebserviceService
    extends Service
{

    private final static URL HELLOWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWEBSERVICESERVICE_EXCEPTION;
    private final static QName HELLOWEBSERVICESERVICE_QNAME = new QName("http://offcn.com/", "HelloWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWEBSERVICESERVICE_WSDL_LOCATION = url;
        HELLOWEBSERVICESERVICE_EXCEPTION = e;
    }

    public HelloWebserviceService() {
        super(__getWsdlLocation(), HELLOWEBSERVICESERVICE_QNAME);
    }

    public HelloWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWEBSERVICESERVICE_QNAME, features);
    }

    public HelloWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWEBSERVICESERVICE_QNAME);
    }

    public HelloWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWEBSERVICESERVICE_QNAME, features);
    }

    public HelloWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWebservice
     */
    @WebEndpoint(name = "HelloWebservicePort")
    public HelloWebservice getHelloWebservicePort() {
        return super.getPort(new QName("http://offcn.com/", "HelloWebservicePort"), HelloWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebservice
     */
    @WebEndpoint(name = "HelloWebservicePort")
    public HelloWebservice getHelloWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://offcn.com/", "HelloWebservicePort"), HelloWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWEBSERVICESERVICE_EXCEPTION!= null) {
            throw HELLOWEBSERVICESERVICE_EXCEPTION;
        }
        return HELLOWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
